name: JAQUP CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build & Test
        run: mvn -B clean verify

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar \
          -Dsonar.projectKey=YOUR_PROJECT_KEY \
          -Dsonar.host.url=http://sonarqube:9000 \
          -Dsonar.login=$SONAR_TOKEN
